require:
  - rubocop-rspec

AllCops:
  Exclude:
    - 'fixtures/**/*'
  TargetRubyVersion: 2.3

# Dot at end of line makes it clearer that the line is not done
Layout/DotPosition:
  EnforcedStyle: trailing

# Test and spec describe blocks can be any size.
# Gem specification can be any size.
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'memory_test_fix.gemspec'

# Require lines to fit in pull requests.
Metrics/LineLength:
  Max: 92

# Prefer parentheses in method definitions
Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses

# Use older RuboCop default
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': ()

# Always use raise to raise exceptions
Style/SignalException:
  EnforcedStyle: only_raise
