language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - ruby-head-clang
  - jruby-9.1.15.0
  - jruby-9.2.5.0
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-9.1.15.0
    - rvm: jruby-9.2.5.0
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: ruby-head-clang

branches:
  only:
    - master
