source 'https://rubygems.org'

gem 'rails', '~> 5.0.0'
gem 'sqlite3', platform: :ruby
gem 'activerecord-jdbcsqlite3-adapter', platform: :jruby
gem 'memory_test_fix', path: '../..'

group :development, :test do
  gem 'spring'
end
