source 'https://rubygems.org'

gem 'rails', '~> 5.2.0.rc1'
gem 'sqlite3', platform: :ruby
gem 'activerecord-jdbcsqlite3-adapter', platform: :jruby
gem 'memory_test_fix', path: '../..'

group :development do
  gem 'spring'
end
